public enum TransactionType {
    SIGNUP,
    OPENCHECKING,
    OPENSAVINGS,
    OPENSECURITIES,
    OPENLOAN,
    CLOSELOAN,
    CHARGEFEE,
    PAYSAVINGSINTEREST,
    ADDLOANINTEREST,
    CLOSE,
    DEPOSIT,
    WITHDRAW,
    TRANSFER,
    PAYLOAN
}
